// import { createStore } from "redux";
import { configureStore } from "@reduxjs/toolkit";
import counterSlice from "./counter";
import authSlice from "./auth";

const store = configureStore({
  // Configuring store with a single slice's reducer
  reducer: {
    counter: counterSlice.reducer,
    auth: authSlice.reducer,
  },
});

// To dispatch new states, toolkit provides us with actions functions these functions return a {} with a type generated by redux.
// These action functions can be called inside the dispatch hook to dispatch an action
export default store;
